<!-- application/layouts/scripts/layout.phtml -->
<!DOCTYPE html>
<html>
<head>

    <meta charset="UTF-8">
    <?php echo $this->headTitle('ZF Test Converter')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php
    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

    echo $this->headMeta()->appendName('theme-color', '#db5945');

    header('Expires: true');
    header('Cache-Control: public true max-age=31536000');
    ?>

    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

    <style type="text/css">
        body, html {
            height: 100%;
        }
        .wrapper {
            width: 100%;
            display: flex;
            flex-direction: column;
            justify-content: center;
            height: 100%;
        }
        div#welcome {
            width: 600px;
            height: 400px;
            border: 2px solid #444444;
            overflow: hidden;
            text-align: center;
            margin: 0 auto;
        }

        div#more-information {
            height: 100%;
        }

        .given, .desired {
            display: block;
            width: 40%;
            height: 100%;
        }

        .given {
            float: left;
        }

        .desired {
            float: right;
        }

        .swap {
            display: block;
            float: left;
            margin: 50px 30px;
        }

        .swap button {
            color: white;
            border-radius: 4px;
            text-shadow: 0 1px 1px rgba(0, 0, 0, 0.2);
            background: rgb(28, 184, 65);
            width: 60px;
            height: 30px;
        }

        p {
            margin: 5px 0;
        }
        .history {
            width: 100%;
            height: auto;
            margin: 10px 0;
            font-size: 90%;
        }
        .dropdown {
            background: url(http://i62.tinypic.com/2e3ybe1.jpg) no-repeat right center;
            height: 34px;
            width: 240px;
        }
        label {
            float: left;
            margin: 5px;
        }
        input[type="text"] {
            width: 240px;
            height: 34px;
        }
        .clear {
            clear:both;
        }
    </style>

</head>
<body>

<div class="wrapper">
    <?php echo $this->layout()->content; ?>
</div>

</body>
</html>
