<!-- application/layouts/scripts/layout.phtml -->
<!DOCTYPE html>
<html>
<head>

    <meta charset="UTF-8">
    <?php header('Expires: true'); ?>
    <?php header('Cache-Control: public true max-age=31536000'); ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>
    <?php echo $this->headMeta()->appendName('theme-color', '#db5945'); ?>
    <?php echo $this->headTitle('ZF Test Converter')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headLink() ->prependStylesheet($this->baseUrl('css/style.css')); ?>
    <?php echo $this->headScript()->prependFile($this->baseUrl('js/jquery-1.9.1.min.js')); ?>

</head>
<body>

<div class="wrapper">
    <?php echo $this->layout()->content; ?>
</div>

</body>
</html>
